version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: l07p@gmx.de  # Change this to your preferred email
      PGADMIN_DEFAULT_PASSWORD: ueber500mal    # Change this to your preferred password
    volumes:
      - /home/ubuntu/dockers/pgadmin/data:/var/lib/pgadmin
    ports:
      - "5050:80"  # Map port 5050 on your host to port 80 in the container (pgAdmin web interface)
    restart: always
